-- Полный список активных кодов ISO 4217
-- Статичный справочник, не содержит курсов обмена.
-- Проверка: SELECT COUNT(*) FROM currencies; → должно быть ~160

INSERT INTO currencies (code, name_ru, name_en) VALUES
('AED', 'Дирхам ОАЭ',                          'UAE Dirham'),
('AFN', 'Афганский афгани',                     'Afghan Afghani'),
('ALL', 'Албанский лек',                        'Albanian Lek'),
('AMD', 'Армянский драм',                       'Armenian Dram'),
('ANG', 'Нидерландский антильский гульден',     'Netherlands Antillean Guilder'),
('AOA', 'Ангольская кванза',                    'Angolan Kwanza'),
('ARS', 'Аргентинское песо',                    'Argentine Peso'),
('AUD', 'Австралийский доллар',                 'Australian Dollar'),
('AWG', 'Арубанский флорин',                    'Aruban Florin'),
('AZN', 'Азербайджанский манат',                'Azerbaijani Manat'),
('BAM', 'Боснийская конвертируемая марка',      'Bosnia-Herzegovina Convertible Mark'),
('BBD', 'Барбадосский доллар',                  'Barbadian Dollar'),
('BDT', 'Бангладешская така',                   'Bangladeshi Taka'),
('BGN', 'Болгарский лев',                       'Bulgarian Lev'),
('BHD', 'Бахрейнский динар',                    'Bahraini Dinar'),
('BMD', 'Бермудский доллар',                    'Bermudian Dollar'),
('BND', 'Брунейский доллар',                    'Brunei Dollar'),
('BOB', 'Боливийский боливиано',                'Bolivian Boliviano'),
('BRL', 'Бразильский реал',                     'Brazilian Real'),
('BSD', 'Багамский доллар',                     'Bahamian Dollar'),
('BTN', 'Бутанский нгултрум',                   'Bhutanese Ngultrum'),
('BWP', 'Ботсванская пула',                     'Botswanan Pula'),
('BYN', 'Белорусский рубль',                    'Belarusian Ruble'),
('BZD', 'Белизский доллар',                     'Belize Dollar'),
('CAD', 'Канадский доллар',                     'Canadian Dollar'),
('CDF', 'Конголезский франк',                   'Congolese Franc'),
('CHF', 'Швейцарский франк',                    'Swiss Franc'),
('CLP', 'Чилийское песо',                       'Chilean Peso'),
('CNY', 'Китайский юань',                       'Chinese Yuan'),
('COP', 'Колумбийское песо',                    'Colombian Peso'),
('CRC', 'Костариканский колон',                 'Costa Rican Colón'),
('CUP', 'Кубинское песо',                       'Cuban Peso'),
('CVE', 'Кабо-вердийское эскудо',               'Cape Verdean Escudo'),
('CZK', 'Чешская крона',                        'Czech Koruna'),
('DJF', 'Джибутийский франк',                   'Djiboutian Franc'),
('DKK', 'Датская крона',                        'Danish Krone'),
('DOP', 'Доминиканское песо',                   'Dominican Peso'),
('DZD', 'Алжирский динар',                      'Algerian Dinar'),
('EGP', 'Египетский фунт',                      'Egyptian Pound'),
('ERN', 'Эритрейская накфа',                    'Eritrean Nakfa'),
('ETB', 'Эфиопский быр',                        'Ethiopian Birr'),
('EUR', 'Евро',                                 'Euro'),
('FJD', 'Фиджийский доллар',                    'Fijian Dollar'),
('FKP', 'Фолклендский фунт',                    'Falkland Islands Pound'),
('GBP', 'Британский фунт стерлингов',           'British Pound Sterling'),
('GEL', 'Грузинский лари',                      'Georgian Lari'),
('GHS', 'Ганский седи',                         'Ghanaian Cedi'),
('GIP', 'Гибралтарский фунт',                   'Gibraltar Pound'),
('GMD', 'Гамбийский даласи',                    'Gambian Dalasi'),
('GNF', 'Гвинейский франк',                     'Guinean Franc'),
('GTQ', 'Гватемальский кетсаль',                'Guatemalan Quetzal'),
('GYD', 'Гайанский доллар',                     'Guyanese Dollar'),
('HKD', 'Гонконгский доллар',                   'Hong Kong Dollar'),
('HNL', 'Гондурасская лемпира',                 'Honduran Lempira'),
('HTG', 'Гаитянский гурд',                      'Haitian Gourde'),
('HUF', 'Венгерский форинт',                    'Hungarian Forint'),
('IDR', 'Индонезийская рупия',                  'Indonesian Rupiah'),
('ILS', 'Израильский новый шекель',             'Israeli New Shekel'),
('INR', 'Индийская рупия',                      'Indian Rupee'),
('IQD', 'Иракский динар',                       'Iraqi Dinar'),
('IRR', 'Иранский риал',                        'Iranian Rial'),
('ISK', 'Исландская крона',                     'Icelandic Króna'),
('JMD', 'Ямайский доллар',                      'Jamaican Dollar'),
('JOD', 'Иорданский динар',                     'Jordanian Dinar'),
('JPY', 'Японская иена',                        'Japanese Yen'),
('KES', 'Кенийский шиллинг',                    'Kenyan Shilling'),
('KGS', 'Киргизский сом',                       'Kyrgyzstani Som'),
('KHR', 'Камбоджийский риель',                  'Cambodian Riel'),
('KMF', 'Коморский франк',                      'Comorian Franc'),
('KPW', 'Северокорейская вона',                 'North Korean Won'),
('KRW', 'Южнокорейская вона',                   'South Korean Won'),
('KWD', 'Кувейтский динар',                     'Kuwaiti Dinar'),
('KYD', 'Доллар Каймановых островов',           'Cayman Islands Dollar'),
('KZT', 'Казахстанский тенге',                  'Kazakhstani Tenge'),
('LAK', 'Лаосский кип',                         'Laotian Kip'),
('LBP', 'Ливанский фунт',                       'Lebanese Pound'),
('LKR', 'Шри-ланкийская рупия',                 'Sri Lankan Rupee'),
('LRD', 'Либерийский доллар',                   'Liberian Dollar'),
('LSL', 'Лесотский лоти',                       'Lesotho Loti'),
('LYD', 'Ливийский динар',                      'Libyan Dinar'),
('MAD', 'Марокканский дирхам',                  'Moroccan Dirham'),
('MDL', 'Молдавский лей',                       'Moldovan Leu'),
('MGA', 'Малагасийский ариари',                 'Malagasy Ariary'),
('MKD', 'Македонский денар',                    'Macedonian Denar'),
('MMK', 'Мьянманский кьят',                     'Myanmar Kyat'),
('MNT', 'Монгольский тугрик',                   'Mongolian Tögrög'),
('MOP', 'Макаосская патака',                    'Macanese Pataca'),
('MRU', 'Мавританская угия',                    'Mauritanian Ouguiya'),
('MUR', 'Маврикийская рупия',                   'Mauritian Rupee'),
('MVR', 'Мальдивская руфия',                    'Maldivian Rufiyaa'),
('MWK', 'Малавийская квача',                    'Malawian Kwacha'),
('MXN', 'Мексиканское песо',                    'Mexican Peso'),
('MYR', 'Малайзийский ринггит',                 'Malaysian Ringgit'),
('MZN', 'Мозамбикский метикал',                 'Mozambican Metical'),
('NAD', 'Намибийский доллар',                   'Namibian Dollar'),
('NGN', 'Нигерийская найра',                    'Nigerian Naira'),
('NIO', 'Никарагуанская кордоба',               'Nicaraguan Córdoba'),
('NOK', 'Норвежская крона',                     'Norwegian Krone'),
('NPR', 'Непальская рупия',                     'Nepalese Rupee'),
('NZD', 'Новозеландский доллар',                'New Zealand Dollar'),
('OMR', 'Оманский риал',                        'Omani Rial'),
('PAB', 'Панамская бальбоа',                    'Panamanian Balboa'),
('PEN', 'Перуанский соль',                      'Peruvian Sol'),
('PGK', 'Папуа-новогвинейская кина',            'Papua New Guinean Kina'),
('PHP', 'Филиппинское песо',                    'Philippine Peso'),
('PKR', 'Пакистанская рупия',                   'Pakistani Rupee'),
('PLN', 'Польский злотый',                      'Polish Złoty'),
('PYG', 'Парагвайский гуарани',                 'Paraguayan Guaraní'),
('QAR', 'Катарский риал',                       'Qatari Riyal'),
('RON', 'Румынский лей',                        'Romanian Leu'),
('RSD', 'Сербский динар',                       'Serbian Dinar'),
('RUB', 'Российский рубль',                     'Russian Ruble'),
('RWF', 'Руандийский франк',                    'Rwandan Franc'),
('SAR', 'Саудовский риял',                      'Saudi Riyal'),
('SBD', 'Доллар Соломоновых островов',          'Solomon Islands Dollar'),
('SCR', 'Сейшельская рупия',                    'Seychellois Rupee'),
('SDG', 'Суданский фунт',                       'Sudanese Pound'),
('SEK', 'Шведская крона',                       'Swedish Krona'),
('SGD', 'Сингапурский доллар',                  'Singapore Dollar'),
('SHP', 'Фунт острова Святой Елены',            'Saint Helena Pound'),
('SLE', 'Сьерра-леонский леоне',                'Sierra Leonean Leone'),
('SOS', 'Сомалийский шиллинг',                  'Somali Shilling'),
('SRD', 'Суринамский доллар',                   'Surinamese Dollar'),
('STN', 'Добра Сан-Томе и Принсипи',            'São Tomé and Príncipe Dobra'),
('SVC', 'Сальвадорский колон',                  'Salvadoran Colón'),
('SYP', 'Сирийский фунт',                       'Syrian Pound'),
('SZL', 'Лилангени Эсватини',                   'Eswatini Lilangeni'),
('THB', 'Тайский бат',                          'Thai Baht'),
('TJS', 'Таджикский сомони',                    'Tajikistani Somoni'),
('TMT', 'Туркменский манат',                    'Turkmenistani Manat'),
('TND', 'Тунисский динар',                      'Tunisian Dinar'),
('TOP', 'Тонганская паанга',                    'Tongan Paʻanga'),
('TRY', 'Турецкая лира',                        'Turkish Lira'),
('TTD', 'Доллар Тринидада и Тобаго',            'Trinidad and Tobago Dollar'),
('TWD', 'Новый тайваньский доллар',             'New Taiwan Dollar'),
('TZS', 'Танзанийский шиллинг',                 'Tanzanian Shilling'),
('UAH', 'Украинская гривна',                    'Ukrainian Hryvnia'),
('UGX', 'Угандийский шиллинг',                  'Ugandan Shilling'),
('USD', 'Доллар США',                           'United States Dollar'),
('UYU', 'Уругвайское песо',                     'Uruguayan Peso'),
('UZS', 'Узбекский сум',                        'Uzbekistani Som'),
('VES', 'Венесуэльский боливар',                'Venezuelan Bolívar Soberano'),
('VND', 'Вьетнамский донг',                     'Vietnamese Đồng'),
('VUV', 'Вануатский вату',                      'Vanuatu Vatu'),
('WST', 'Самоанская тала',                      'Samoan Tālā'),
('XAF', 'Франк CFA Центральной Африки',         'Central African CFA Franc'),
('XCD', 'Восточно-карибский доллар',            'East Caribbean Dollar'),
('XOF', 'Франк CFA Западной Африки',            'West African CFA Franc'),
('XPF', 'Франк CFP',                            'CFP Franc'),
('YER', 'Йеменский риал',                       'Yemeni Rial'),
('ZAR', 'Южноафриканский рэнд',                 'South African Rand'),
('ZMW', 'Замбийская квача',                     'Zambian Kwacha'),
('ZWL', 'Зимбабвийский доллар',                 'Zimbabwean Dollar')
ON CONFLICT (code) DO NOTHING;
